source 'https://rubygems.org'

gem 'watir-webdriver'
gem 'page-object'
gem 'selenium-webdriver'
gem 'cucumber'
gem 'require_all'
gem 'rake'
gem 'rspec-expectations'
gem 'pry'
gem 'pry-remote'
gem 'pry-nav'
